WIP: Linesearch
vchuravy/NewtonKrylov.jl pull request #1
Opened 2024-11-19 10:09 UTC by vchuravy

2026-04-17 13:24 UTC, vchuravy commented
Current results:

| N | NoLineSearch (iterations)  |   time (s)  | BacktrackingLineSearch (iterations) |  time | 
| -- | ------------------   | --------------------------------  |   --- | ---- |
| 6 | 21 | 0.00007121 |  115 | 0.000415178 |
| 7 | 66 | 0.000129203 | 182 | 0.003204213 |
| 8 | 56 | 0.000106193 | 282 | 0.001153047 |
| 9 | X |  | 465 |   0.00423094 |
| 10 | X |  | 884 |  0.006603219 |
| 11 | X  |  | 1568 | 0.01126607 |
| 12 | X |   | 2346 |  0.024341541 |

Pal et.al. report that for N=10 their backtracking implementation does not converge. They use abstol = 1e-8 we use 1e-12

2026-04-17 19:18 UTC, ranocha requested changes
Thanks! Can you please add some real tests to `test` as well?

2026-04-17 19:18 UTC, ranocha commented on src/Ariadne.jl
> +        krylov_solve!(workspace, J, neg_res; kwargs...)
Why did you change this?

2026-04-17 19:18 UTC, ranocha commented on src/linesearches.jl
> +Linesearch may update the solution `u` and the residual `res` in-place,
```suggestion
Line search may update the solution `u` and the residual `res` in-place,
```

2026-04-17 19:18 UTC, ranocha commented on src/linesearches.jl
> +After SIAMFANLEquations.jl
Can you please provide a bit more concrete reference?


```suggestion
## References

- Kelley, C. T. (2022).
  Solving nonlinear equations with iterative methods:
  Solvers and examples in Julia.
  Society for Industrial and Applied Mathematics.
- <https://github.com/ctkelley/SIAMFANLEquations.jl>
```

Please add the chapter or something like that wherever you took the idea from.

2026-04-17 19:18 UTC, ranocha commented on src/linesearches.jl
> +        # @info "Line search iteration" lambda n_res n_res_prior armijo=((1 - alpha * lambda) * n_res_prior)
```suggestion
```

2026-04-17 19:18 UTC, ranocha commented on src/linesearches.jl
> +    alpha = 1.e-4
```suggestion
    alpha = 1.0e-4
```

2026-04-17 19:18 UTC, ranocha commented on src/linesearches.jl
> +function (ls::BacktrackingLineSearch)(F!, res, n_res_prior, u, p, d)
```suggestion
function (ls::BacktrackingLineSearch)(F!, res, norm_res_prior, u, p, d)
```

`n_` is often used for some natural number

2026-04-17 19:18 UTC, ranocha commented on src/linesearches.jl
> +    n_res = Inf
```suggestion
    norm_res = norm_res_prior
```

2026-04-17 19:18 UTC, ranocha commented on src/linesearches.jl
> +        n_res = norm(res)
```suggestion
        norm_res = norm(res)
```

2026-04-17 19:18 UTC, ranocha commented on src/linesearches.jl
> +    return n_res
```suggestion
        if norm_res <= (1 - alpha * lambda) * norm_res_prior
            u .= u_trial
            return norm_res
        end

        lambda *= 0.5
    end
    u .= u_trial
    return norm_res
```

2026-04-17 19:18 UTC, ranocha commented on src/linesearches.jl
> +# https://github.com/ctkelley/SIAMFANLEquations.jl/blob/e5603e177dd007b065265641fb232d54020c4282/src/Tools/armijo.jl#L57
```suggestion
# TODO: SIAMFANL is using a parabolic line search
# https://github.com/ctkelley/SIAMFANLEquations.jl/blob/e5603e177dd007b065265641fb232d54020c4282/src/Tools/armijo.jl#L57
```

2026-04-18 10:38 UTC, vchuravy commented on src/Ariadne.jl
> +        krylov_solve!(workspace, J, neg_res; kwargs...)
So that the line search doesn't need to keep the direction change in mind.

2026-04-18 10:39 UTC, vchuravy commented on src/linesearches.jl
> +function (ls::BacktrackingLineSearch)(F!, res, n_res_prior, u, p, d)
We currently use `n_res` consistently in the rest of the code.

2026-04-18 14:04 UTC, ranocha commented on src/linesearches.jl
> +function (ls::BacktrackingLineSearch)(F!, res, n_res_prior, u, p, d)
Do you have a strong opinion on keeping `n_res`? If so, I am fine with this. I was just wondering when reading the line `n_res = Inf` below why you introduce a type instability by assigning a `Float64` to something that will be an `Integer`.

2026-04-20 19:24 UTC, ranocha approved these changes
Thanks - also for your patience with an old guy biased by ancient FORTRAN conventions...

2026-04-20 19:24 UTC, merged